name: Build veraPDF

on:
  push:
    branches: [main]
  pull_request:

jobs:
  verapdf:
    runs-on: ubuntu-latest
    env:
      INSIDE_CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install veraPDF
        run: |
          wget https://software.verapdf.org/rel/verapdf-installer.zip
          unzip verapdf-installer.zip
          cd verapdf-greenfield-1.28.2
          java -jar verapdf-izpack-installer-1.28.2.jar install path="$HOME/verapdf"
